name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: version
    attributes:
      label: Version of the software
      description: What version of the software were you using when the bug occurred?
      placeholder: ex. 0.1.0
    validations:
      required: true
  - type: input
    id: os
    attributes:
      label: Operating system
      description: What operating system is your OB2 running on?
      placeholder: ex. Windows 10
    validations:
      required: true
  - type: input
    id: browser
    attributes:
      label: Browser / Native
      description: Which browser are you using to access the web interface of OB2? If you are using the native client, just write Native
      placeholder: ex. Chrome 91
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: lolicode
    attributes:
      label: Relevant LoliCode if needed
      description: Please copy and paste any relevant LoliCode to reproduce the issue. This will be automatically formatted into code, so no need for backticks.
      render: shell
